/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Procedimiento;
import Modelo.ProcedimientoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import Modelo.*;
import javax.swing.JOptionPane;
import Vista.*;

/**
 *
 * @author Gustavo
 */
public class SolicitarCita extends javax.swing.JInternalFrame {

    public static String IDProcedimiento;
    public static String IDVet;
    private Mapa2 coordenadas;
    
    public static String latCliente;
    public static String lonCliente;
    public static String latVet;
    public static String lonVet;
    /**
     * Creates new form NuevaCita_Procedimiento
     */
    public SolicitarCita() {
        initComponents();
    }
    
    public void ObtenerDatos(){
        List<Procedimiento> procedimientos = new ProcedimientoDAO().obtenerRegistrosLista();
        DefaultTableModel modelo = new DefaultTableModel();
        String [] columnas= {"Nombre", "ID", "Tipo", "Monto","Monto Domicilio","Descripcion"};
        modelo.setColumnIdentifiers(columnas);
        for(Procedimiento proced : procedimientos){
            String [] renglon = {proced.getNombreProcedimiento(),
                proced.getIDProcedimiento(),
                proced.getTipo(),
                Integer.toString(proced.getMontoUnitario()),
                Integer.toString(proced.getMontoServAdom()),
                proced.getDescripcionProcedimiento(),
                Integer.toString(proced.getCodigoCategoria()),
                Integer.toString(proced.getIDPaciente())    };
            modelo.addRow(renglon);
            }
       jTable1.setModel(modelo);
        }
    
    public void ObtenerDatosVet(String IDProcedimiento){
        List<Veterinario> veterinarios = new VeterinarioDAO().ObtenerVetProcedimiento(IDProcedimiento);
        DefaultTableModel modelo = new DefaultTableModel();
        String [] columnas= {"Cedula", "ID", "Nombre", "Apellido", "Calificacion","Horario","Sitio Web"};
        modelo.setColumnIdentifiers(columnas);
        for(Veterinario veterinario : veterinarios){
            String [] renglon = {
                Integer.toString(veterinario.getCedula()),
                veterinario.getIDVet(),
                veterinario.getNombre(),
                veterinario.getApellido(),
                Integer.toString(veterinario.getCalificacion()),
                veterinario.getHorarioAtencion(),
                veterinario.getSitioWeb()
            };
            modelo.addRow(renglon);
            
            }
       jTable2.setModel(modelo);
        }
    
    public String Latitud (int Cedula){
        List<UbicacionPersona> latitudes = new UbicacionPersonaDAO().consultarLatitud(Cedula);
        String lat = "";
        for (UbicacionPersona latitud: latitudes){
            lat = latitud.getLatitud();
            //System.out.println(lat + "   Latitud");
        }
       return lat;        
    }
    
    
    public String Longitud (int Cedula){
        //System.out.println(Cedula);
        List<UbicacionPersona> longitudes = new UbicacionPersonaDAO().consultarLongitud(Cedula);
        String lon = "";
        for (UbicacionPersona longitud : longitudes){
            lon = longitud.getLongitud();
            //System.out.println(lon);
        }
        return lon;        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Selecciona Procedimiento/Servicio");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Seleccione el procedimiento o servicio que desea agendar en su cita");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setText("Seleccione el veterinario que desea consultar");

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Modalidad de consulta:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En clínica", "A domicilio" }));

        jButton3.setText("Finalizar");

        jLabel4.setText("Digite su cedula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(53, 53, 53)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int fila = jTable1.getSelectedRow();      
       this.IDProcedimiento = (String)jTable1.getValueAt(fila, 1);
       this.ObtenerDatosVet(IDProcedimiento);
       JOptionPane.showMessageDialog(rootPane, "Procedimeinto/Servicio registrado");
       
       //Crear una variable que almacene el dato que requiero de procedimeintos
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int fila = jTable2.getSelectedRow();
        System.out.println(fila + " num fila seleccionada");
        
        
        this.IDVet = (String)jTable2.getValueAt(fila, 1); 
        System.out.println(IDVet + " obtenido de la tabla 2");
        
        String CedulaVet = (String)jTable2.getValueAt(fila, 0);
        System.out.println(fila + " verifcicar num fila seleccionada");
        System.out.println(CedulaVet + " obtenido de la tabla 2");
        
        String CedulaCliente = jTextField1.getText();
        System.out.println(CedulaCliente + " obteneido del textfield");
 
        
        SolicitarCita.latCliente = this.Latitud(Integer.parseInt(CedulaCliente));
        System.out.println(latCliente + " latCLiente");
        
        SolicitarCita.lonCliente = this.Longitud(Integer.parseInt(CedulaCliente));
        System.out.println(lonCliente + " lonCliente");
        
        SolicitarCita.latVet = this.Latitud(Integer.parseInt(CedulaVet));
        System.out.println(latVet + " latVet");
        
        SolicitarCita.lonVet = this.Longitud(Integer.parseInt(CedulaVet));
        System.out.println(lonVet + " lonVet");
        
        
        Mapa2 mapa = new Mapa2();
        mapa.setVisible(true);
        
        
        
        
  
        JOptionPane.showMessageDialog(rootPane, "Veterinario registrado");
    }//GEN-LAST:event_jButton2ActionPerformed

    public static String getLatCliente() {
        return latCliente;
    }

    public static String getLonCliente() {
        return lonCliente;
    }

    public static String getLatVet() {
        return latVet;
    }

    public static String getLonVet() {
        return lonVet;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
